name: agro
channels:
  - defaults
  - https://download.pytorch.org/whl/cu118
dependencies:
  - python
  - pip
  - pip:
    - geopandas
    - pandas
    - torch
    - torchvision
    - transformers
    - leafmap
    - streamlit-vis-timeline
    - setuptools
    - opencv-python
    - matplotlib