name: agro
channels:
  - defaults
dependencies:
  - python=3.11.8
  - pip
  - pip:
    - geopandas==1.0.1
    - pandas==2.2.2
    - leafmap
    - streamlit-vis-timeline==0.3.0    
    - setuptools==71.0.4  